# Generated by Django 6.1 on 2026-08-06 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=10)),
                ('resultado', models.CharField(choices=[('ganada', 'Ganada'), ('perdida', 'Perdida')], max_length=10)),
                ('tiempo_usado', models.PositiveIntegerField()),
                ('intentos_restantes', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
